name: Deploy to Crates.io

on:
  release:
    types: [ published, edited ]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: dtolnay/rust-toolchain@stable
        - name: build
          run: cargo build --release
        - name: publish
          run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}